name: donJoomla
description: Free, open-source Joomla! Extensions.
baseurl: /
image: http://donjoomla.com/images/donjoomla.png
url: http://donjoomla.com
locale: en_GB
timezone: Europe/London
com_timeline:
    dl: https://github.com/donJoomla/com_timeline/releases/download/v1.0/com_timeline-1.0-J3.zip
    ver: 1.0
mod_jforms:
    dl: https://github.com/donJoomla/jforms/releases/download/v1.6.2/mod_jforms_162_j25.zip
    ver: 1.6.2
pkg_jforms: 
    dl: https://github.com/donJoomla/jforms/releases/download/v1.6.2/pkg_jforms_full_162_j25.zip
    ver: 1.6.2
plg_system_jforms: 
    dl: https://github.com/donJoomla/jforms/releases/download/v1.6.2/plg_system_jforms_111_j25.zip
    ver: 1.1.1
plg_jforms_googlespreadsheet:
    dl: https://github.com/donJoomla/jforms/releases/download/v1.6.2/plg_jforms_googlespreadsheet_121_j25.zip
    ver: 1.2.1
plg_jforms_ymlp: 
    dl: https://github.com/donJoomla/jforms/releases/download/v1.6.2/plg_jforms_ymlp_111_j25.zip
    ver: 1.1.1
