name: donJoomla
title: donJoomla &middot; Free Joomla! Extensions
description: Free, open-source Joomla! Extensions.
baseurl: /
image: http://donjoomla.com/images/donjoomla.png
url: http://donjoomla.com
locale: en_GB
timezone: Europe/London
markdown: kramdown
gems:
  - jekyll-sitemap
com_timeline:
    dl: https://github.com/donJoomla/com_timeline/releases/download/v1.0/com_timeline-1.0-J3.zip
    ver: 1.0
mod_jforms:
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/mod_jforms.zip
    ver: 1.6.5
pkg_jforms: 
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/pkg_jforms.zip
    ver: 1.6.5
plg_system_jforms: 
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/plg_system_jforms.zip
    ver: 1.1.1
plg_jforms_googlespreadsheet:
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/plg_jforms_googlespreadsheet.zip
    ver: 1.2.1
plg_jforms_ymlp: 
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/plg_jforms_ymlp.zip
    ver: 1.1.1
plg_jforms_mailchimp: 
    dl: https://github.com/donJoomla/jforms/releases/download/1.6.5/plg_jforms_mailchimp.zip
    ver: 1.1
demo_url: http://donlabs.com/demo/j3/

disqus_shortname: donjoomla
author: Adam Bouqdib
gems:
  - jekyll-sitemap
relative_permalinks: false